WebTemplate/Models/DynamicLookup/Index.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebTemplate.Models.DynamicLookup
{
    public class Index : BaseModel
    {
        public string Key { get; set; }
        public Lookups? LookupName { get; set; }
        public dynamic DynamicList { get; set; }
        public bool IsDefault { get; set; }
    }
}

WebTemplate/Models/DynamicLookup/LookupData.cs
namespace WebTemplate.Models.DynamicLookup
{
    public class LookupData
    {
        public Lookups LookupName { get; set; }
        public dynamic Data { get; set; }
    }
}

WebTemplate/Models/DynamicLookup/LookupList.cs
using Newtonsoft.Json;
using ProcessLayer.Entities;
using ProcessLayer.Processes;
using ProcessLayer.Processes.Lookups;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebTemplate.Models.DynamicLookup
{
    public enum Lookups
    {
        Position,
        Location,
        Deduction,
        Payroll_Parameters,
        Non_Working_Days,
        Schedule,
        Tax_Table,
        Late_Deduction,
        Leave_Type, 
        Leave_Default_Credits,
        PhilHealth,
        SSS,
        HDMF,
        Department_Position,
        Non_Taxable_Days,
        Vessel,
        Civil_Status,
        Code_of_Discipline,
        Contact_No_Type,
        Educational_Level,
        Employment_Status,
        Employment_Type,
        Memo_Status,
        Memo_Type,
        Nationality,
        Relationship,
        Religion,
        Crew_Position_Salary
    }
    public enum LookupDataType
    {
        rate,
        amount,
        number,
        text,
        boolean,
        model,
        date,
        monthday,
        time,
        year
    }
    public class LookupSetting
    {
        public string Name { get; }
        public bool ReadOnly { get; }
        public string ReadOnlyCheck { get { return ReadOnly ? "disabled" : ""; } }
        public string ReadOnlyText { get { return ReadOnly ? "readonly" : ""; } }
        public LookupDataType Type { get; }
        public string Display { get; }
        public LookupSetting ClassSetting { get; }
        public dynamic LookupSource { get; }
        public string LookupSourceData { get; }
        public bool HasDefault { get; }
        public LookupSetting(string name = "Description",
                             string display = null,
                             LookupDataType type = LookupDataType.text,
                             LookupSetting classSetting = null,
                             dynamic lookupSource = null,
                             string lookupSourceData = null,
                             bool readOnly = false, 
                             bool hasDefault = false)
        {
            Name = name;
            Type = type;
            ClassSetting = classSetting;
            Display = display ?? name;
            LookupSource = lookupSource;
            ReadOnly = readOnly;
            LookupSourceData = lookupSourceData;
            HasDefault = hasDefault;
        }

    }
    public class LookupActions
    {
        public bool Add { get; }
        public bool Edit { get; }
        public bool Delete { get; }
        public bool Pagination { get; }
        public bool Search { get; }

        public LookupActions(bool add = true, bool edit = true, bool delete = true, bool pagination = true, bool search = true)
        {
            Add = add;
            Edit = edit;
            Delete = delete;
            Pagination = pagination;
            Search = search;
        }
    }
    public static class LookupHelperExtension
    {
        public static void Add(this List<KeyValuePair<Lookups, string>> lookupLists, Lookups lookup, string value)
        {
            lookupLists.Add(new KeyValuePair<Lookups, string>(lookup, value));
        }
        public static void Add(this List<KeyValuePair<Lookups, List<LookupSetting>>> lookupListItems, Lookups lookup, params LookupSetting[] lookupSettings)
        {
            lookupListItems.Add(new KeyValuePair<Lookups, List<LookupSetting>>(lookup, lookupSettings.ToList()));
        }
        public static void Add(this List<KeyValuePair<Lookups, LookupActions>> lookupActions, Lookups lookup, LookupActions lookupAction)
        {
            lookupActions.Add(new KeyValuePair<Lookups, LookupActions>(lookup, lookupAction));
        }
    }
    public static class LookupHelper
    {
        public static readonly List<KeyValuePair<Lookups, string>> LookupLists = Enum.GetValues(typeof(Lookups)).Cast<Lookups>().Select(x => new KeyValuePair<Lookups, string>(x, x.ToString().Replace("_", " "))).ToList();

        public static readonly List<LookupSetting> DefaultLookupListItems = new() { new LookupSetting() };

        public static readonly List<KeyValuePair<Lookups, List<LookupSetting>>> LookupListItems = new List<KeyValuePair<Lookups, List<LookupSetting>>>()
        {
            { Lookups.Position
                , new LookupSetting()
                , new LookupSetting("Abbreviation")
                , new LookupSetting("PersonnelType", "Personnel Type", LookupDataType.model, new LookupSetting(),  PersonnelTypeProcess.Instance, "PersonnelTypeID")
                , new LookupSetting("AllowApprove", "Allow Approve", LookupDataType.boolean) },
            { Lookups.Location
                , new LookupSetting("Prefix")
                , new LookupSetting()
                , new LookupSetting("HazardRate", "Hazard Rate", LookupDataType.number)
                , new LookupSetting("RequiredTimeLog", "Required Time Log", LookupDataType.boolean)
                , new LookupSetting("OfficeLocation", "Office Location", LookupDataType.boolean)
                , new LookupSetting("WarehouseLocation", "Warehouse Location", LookupDataType.boolean)
                , new LookupSetting("WithHolidayAndSunday", "With Holiday And Sunday (Outer Port)", LookupDataType.boolean)
                , new LookupSetting("WithAdditionalForExtension", "With Additional For Extension (Outer Port)", LookupDataType.boolean)
                , new LookupSetting("InternationalLocation", "International Location", LookupDataType.boolean) },
            { Lookups.Late_Deduction
                , new LookupSetting("TimeIn", "Time In", LookupDataType.time) 
                , new LookupSetting("DeductedHours", "Deducted Hours", LookupDataType.number) },
            { Lookups.Deduction
                , new LookupSetting(readOnly: true)
                , new LookupSetting("GovernmentDeduction", "Government Deduction", LookupDataType.boolean, readOnly: true)
                , new LookupSetting("Deduct", "Cutoff", LookupDataType.model, new LookupSetting(),  WhenToDeductProcess.Instance, "WhenToDeduct") },
            { Lookups.Leave_Type
                , new LookupSetting()
                , new LookupSetting("BulkUse", "Bulk Use", LookupDataType.boolean)
                , new LookupSetting("HasDocumentNeeded", "Has Document Needed", LookupDataType.boolean)
                , new LookupSetting("CNBNoteFirst", "CNB Note", LookupDataType.boolean)
                , new LookupSetting("IsMidYear", "Is Mid Year", LookupDataType.boolean)
                , new LookupSetting("DateStart", "Date", LookupDataType.monthday)},
            { Lookups.Leave_Default_Credits
                , new LookupSetting("LeaveType", "Leave Type", LookupDataType.model, new LookupSetting(), LeaveTypeProcess.Instance, "LeaveTypeID")
                , new LookupSetting("MinYearsInService", "Min Years In Service", LookupDataType.number)
                , new LookupSetting("MaxYearsInService", "Max Years In Service", LookupDataType.number)
                , new LookupSetting("Credits", "Credits (No of Days)", LookupDataType.number)},
            { Lookups.Payroll_Parameters
                , new LookupSetting("DisplayName", "Name", readOnly: true)
                , new LookupSetting("Value") },
            { Lookups.Non_Working_Days
                , new LookupSetting()
                , new LookupSetting("Day", "Date", type: LookupDataType.date)
                , new LookupSetting("StartTime", "Start Time", LookupDataType.time)
                , new LookupSetting("EndTime", "End Time", LookupDataType.time)
                , new LookupSetting("Type", null, LookupDataType.model, new LookupSetting(), NonWorkingTypeProcess.Instance, "NonWorkingType")
                , new LookupSetting("Yearly", type: LookupDataType.boolean)
                , new LookupSetting("IsGlobal", "Global", LookupDataType.boolean)
                , new LookupSetting("Location", null, LookupDataType.model, new LookupSetting(), LocationProcess.Instance, "LocationID", hasDefault: true) },
             { Lookups.Schedule
                , new LookupSetting()
                , new LookupSetting("TimeIn", "Time In", LookupDataType.time)
                , new LookupSetting("TimeOut", "Time Out", LookupDataType.time)
                , new LookupSetting("BreakTime", "Breaktime", LookupDataType.time)
                , new LookupSetting("BreakTimeHour", "Breaktime Hours", LookupDataType.number)
                , new LookupSetting("TotalWorkingHours", "Total Working Hours", LookupDataType.number)
                , new LookupSetting("AtHome", "At Home", LookupDataType.boolean)
                , new LookupSetting("MustBePresentOnly", "Present Only", LookupDataType.boolean) },
             { Lookups.Tax_Table
                , new LookupSetting("TaxSchedule", "Tax Schedule", LookupDataType.model, new LookupSetting(), TaxScheduleProcess.Instance, "TaxScheduleID")
                , new LookupSetting("MinimumIncome", "Minimum Income", LookupDataType.amount)
                , new LookupSetting("MaximumIncome", "Maximum Income", LookupDataType.amount)
                , new LookupSetting("FixedTax", "Fixed Tax", LookupDataType.amount)
                , new LookupSetting("ExcessOver", "Excess Over", LookupDataType.amount)
                , new LookupSetting("AdditionalTax", "Tax Rate", LookupDataType.rate)
                , new LookupSetting("EffectiveStartDate", "Effective Start Date", LookupDataType.date)
                , new LookupSetting("EffectiveEndDate", "Effective End Date", LookupDataType.date) },
             { Lookups.PhilHealth
                , new LookupSetting("MinSalary", "Minimum Salary", LookupDataType.amount)
                , new LookupSetting("MaxSalary", "Maximum Salary", LookupDataType.amount)
                , new LookupSetting("Share", "Share", LookupDataType.amount)
                , new LookupSetting("Rate", "Rate", LookupDataType.rate)

WebTemplate/Models/Searchable/Search.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using WebTemplate.Models.Groups;

namespace WebTemplate.Models.Searchable
{
    public class Search
    {
        public Personnels Personnels { get; set; } = new Personnels();
        public string Key { get; set; }
    }
}

WebTemplate/Controllers/DynamicLookup/DynamicLookupController.cs
using Newtonsoft.Json;
using ProcessLayer.Helpers;
using ProcessLayer.Processes;
using ProcessLayer.Processes.Lookups;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebTemplate.Models.DynamicLookup;

namespace WebTemplate.Controllers.DynamicLookup
{
    public class DynamicLookupController : BaseController
    {
        // GET: DynamicLookup
        public ActionResult Index(Index model)
        {
            if (model.LookupName == null) model.LookupName = Lookups.Position;
            var process = GetProcess(model.LookupName.Value);
            model.Page = model.Page > 1 ? model.Page : 1;
            int PageCount;
            if (LookupHelper.DynamicLookups.Contains(model.LookupName ?? Lookups.Position))
            {
                model.DynamicList = process.Filter(model.LookupName?.ToString().Replace('_', ' '), model.Key, model.Page, model.GridCount, out PageCount);
                model.PageCount = PageCount;
            }
            else
            {
                model.DynamicList = process.Filter(model.Key, model.Page, model.GridCount, out PageCount);
                model.PageCount = PageCount;
            }

            if(model.Page > model.PageCount)
            {
                model.Page = 1;
                if (LookupHelper.DynamicLookups.Contains(model.LookupName ?? Lookups.Position))
                {
                    model.DynamicList = process.Filter(model.LookupName?.ToString().Replace('_', ' '), model.Key, model.Page, model.GridCount, out PageCount);
                    model.PageCount = PageCount;
                }
                else
                {
                    model.DynamicList = process.Filter(model.Key, model.Page, model.GridCount, out PageCount);
                    model.PageCount = PageCount;
                }
            }

            if (Request.IsAjaxRequest())
            {
                ModelState.Clear();
                return PartialViewCustom("_Search", model);
            }
            else
            {
                return ViewCustom("Index", model);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Get(dynamic id,  Lookups lookup)
        {
            dynamic xid = null;
            try { xid = id[0]; } catch { }
            try
            {
                LookupData model = new LookupData
                {
                    LookupName = lookup,
                };

                var process = GetProcess(lookup);

                if (LookupHelper.DynamicLookups.Contains(lookup))
                {
                    model.Data = xid is null ? null : process.Get(lookup.ToString().Replace('_', ' '), id[0]);
                }
                else
                {
                    model.Data = xid is null ? null : process.Get(id[0]);
                }


                ModelState.Clear();
                return PartialViewCustom("_DynamicLookup", model);
            }
            catch (Exception ex)
            {
                return Json(new { msg = false, res = ex.GetActualMessage() });
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Save(string item, Lookups lookup)
        {
            try
            {
                var process = GetProcess(lookup);

                if (LookupHelper.DynamicLookups.Contains(lookup))
                {
                    process.CreateOrUpdate(lookup.ToString().Replace('_', ' '), item, User.UserID);
                }
                else
                {
                    process.CreateOrUpdate(item, User.UserID);
                }

                return Json(new { msg = true, res = "Saved" });
            }
            catch (Exception ex)
            {
                return Json(new { msg = false, res = ex.GetActualMessage() });
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public JsonResult Delete(dynamic id, Lookups lookup)
        {
            if (id != null)
            {
                try
                {
                    var process = GetProcess(lookup);

                    if (LookupHelper.DynamicLookups.Contains(lookup))
                    {
                        process.Delete(lookup.ToString().Replace('_', ' '), id[0], User.UserID); ;
                    }
                    else
                    {
                        process.Delete(id[0], User.UserID);
                    }

                    return Json(new { msg = true, res = "Delete Success" });
                }
                catch
                {
                    return Json(new { msg = false, res = $"{lookup.ToString().Replace('_', ' ')} not found." });
                }
            }
            else
            {
                return Json(new { msg = false, res = $"{lookup.ToString().Replace('_', ' ')} not found." });
            }
        }

        [NonAction] 
        public dynamic GetProcess(Lookups lookup)
        {
            switch (lookup)
            {
                case Lookups.Position:
                    return PositionProcess.Instance;
                case Lookups.Location:
                    return LocationProcess.Instance;
                case Lookups.Late_Deduction:
                    return LateDeductionProcess.Instance;
                case Lookups.Deduction:
                    return DeductionProcess.Instance;
                case Lookups.Leave_Type:
                    return LeaveTypeProcess.Instance;
                case Lookups.Payroll_Parameters:
                    return ParametersProcess.Instance;
                case Lookups.Non_Working_Days:
                    return NonWorkingDaysProcess.Instance;
                case Lookups.Schedule:
                    return ScheduleTypeProcess.Instance;
                case Lookups.Tax_Table:
                    return TaxTableProcess.Instance;
                case Lookups.PhilHealth:
                    return PhilHealthProcess.Instance;
                case Lookups.HDMF:
                    return HDMFProcess.Instance;
                case Lookups.SSS:
                    return SSSProcess.Instance;
                case Lookups.Department_Position:
                    return DepartmentPositionProcess.Instance;
                case Lookups.Vessel:
                    return VesselProcess.Instance;
                case Lookups.Non_Taxable_Days:
                    return NonTaxableDayProcess.Instance;
                case Lookups.Leave_Default_Credits:
                    return LeaveDefaultCreditsProcess.Instance;
                case Lookups.Crew_Position_Salary:
                    return CrewPositionSalaryProcess.Instance;
                default:
                    return DynamicLookupProcess.Instance;
            }
        }
    }
}

WebTemplate/Views/DynamicLookup/DynamicLookup/Index.cshtml
@model WebTemplate.Models.DynamicLookup.Index
@using WebTemplate.Models.DynamicLookup
@{
    var credential = (Session["CredentialPages"] as DataAccessLayer.Security.CredentialPages);
    var PageAccess = credential.GetPage("DynamicLookup/DynamicLookup") ?? new DataAccessLayer.System.Page();

    ViewBag.title = PageAccess.PageName;
}

<div class="wrapper wrapper-content">
    <div class="page-heading">
        <div class="col-lg-8">
            @Html.Partial("~/Views/Shared/_Breadcrumbs.cshtml", PageAccess)
        </div>
        <div class="col-lg-4">
            <div class="title-action">
            </div>
        </div>
    </div>
    <div class="" style="margin-top: 80px;">
        @if (PageAccess.View)
        {
            <div id="lookup_form">
                @Html.Partial("~/Views/DynamicLookup/DynamicLookup/_Search.cshtml")
            </div>
        }
    </div>
</div>


<div class="modal inmodal custom-modal" id="dynamic_modal" data-backdrop="static" data-keyboard="false" tabindex="" role="dialog" aria-hidden="true">
    <div class="vertical-alignment-helper">
        <div class="modal-center vertical-align-center">
            <div class="modal-content animated fadeInUp modal-width-50">
                <div class="modal-header">
                    <h5 class="modal-title">Manage Lookup</h5>
                    <button type="button" id="dynamic_modal_close" class="close" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body" id="modal_body" style="max-height: 750px; background-color: #fff; overflow: auto;">
                    <div class="body"></div>
                </div>
                <div class="modal-footer">
                    <button class="btn btn-primary" id="btn_save">Save</button>
                </div>
            </div>
        </div>
    </div>
</div>

<script>
    $(document).ready(function () {
        $("#dynamic_modal_close").on("click", closeModal);
        events();
    });

    $('.pages').click(function () {
        $('#hid_page').val($(this).val())
        search();
    })

    function events() {
        $(".pages").off('click').on('click', nextPage);
        $("#lookupname").off('change').on('change', lookupChange);
        $("#btn_search").off('click').on('click', search);
        $(".btn_delete").off('click').on('click', deleteItem);
        $(".btn_edit").off('click').on('click', editItem);
        $("#btn_add").off('click').on('click', addItem);
        $("#btn_save").off('click').on('click', saveItem);
        $('.search_key').off('keydown').on('keydown',
            function () {
                if (event.keyCode == 13) {
                    $('#btn_search').click();
                }
            });
        Select2Override();
    }

    function closeModal() {
        $('#dynamic_modal').modal('hide');
    }

    function lookupChange() {
        get("LookupName=" + $(this).val());
    }

    function search() {
        $('#form_search_params input[name="Page"]').val(1);
        get($('#form_search_params *').serialize());
    }

    function nextPage() {
        var params = "LookupName=" + $("#hid_lookupname").val() + "&Key=" + $("#hid_key").val() + "&Page=" + $(this).val();
        get(params);
    }

    function get(params) {
        $.ajax({
            url: '@Url.Action("Index", "DynamicLookup")',
            data: params,
            type: "GET",
            cache: false,
            beforeSend: function () {
                ShowLoadingScreen();
            },
            complete: function () {
                RemoveLoadingScreen();
            },
            success: function (response) {
                if (response.msg == null) {
                    $('#lookup_form').html(response);
                    events();
                } else {
                    toastr.error(response.res);
                }
            },
            error: function () {
                toastr.error('AJAX backend error', 'An error has occured.');
            }
        });
    }

    function deleteItem() {
        var tr = $(this).closest('tr')

        swal({
                title: "Are you sure?",
                text: "Delete this Item?",
                type: "warning",
                showCancelButton: true,
                confirmButtonText: "Yes",
                cancelButtonText: "No",
                closeOnConfirm: true,
                closeOnCancel: true
            },
            function (isConfirm) {
                if (isConfirm) {
                    var value = tr.attr('tpj-key');
                    var lookup = $("#hid_lookupname").val();
                    var token = $('@Html.AntiForgeryToken()').val();
                    $.ajax({
                        url: '@Url.Action("Delete", "DynamicLookup")',
                        data: {
                            id: value,
                            lookup,
                            __RequestVerificationToken: token,
                        },
                        dataType: "JSON",
                        type: "POST",
                        cache: false,
                        beforeSend: function () {
                            ShowLoadingScreen();
                        },
                        complete: function () {
                            RemoveLoadingScreen();
                        },
                        success: function (response) {
                            if (response.msg) {
                                toastr.success(response.res);
                                var params = "LookupName=" + $("#hid_lookupname").val() + "&Key=" + $("#hid_key").val() + "&Page=" + $("#hid_page").val();
                                get(params);
                            } else {
                                toastr.error(response.res);
                            }
                        },
                        error: function () {
                            toastr.error('AJAX backend error', 'An error has occured.');
                        }
                    });
                }
            });
    }

    function addItem() {
        getItem();
    }

    function editItem() {
        var tr = $(this).closest('tr')
        console.log(tr.attr('tpj-key'));
        getItem(tr.attr('tpj-key'));
    }

    function getItem(id) {
        var lookup = $("#hid_lookupname").val();
        var token = $('@Html.AntiForgeryToken()').val();

        $.ajax({
            url: '@Url.Action("Get", "DynamicLookup")',
            data: {
                id: id,
                lookup,
                __RequestVerificationToken: token,
            },
            type: "POST",
            cache: false,
            beforeSend: function () {
                ShowLoadingScreen();
            },
            complete: function () {
                RemoveLoadingScreen();
            },
            success: function (response) {
                if (response.msg == null) {
                    $('#dynamic_modal .modal-body').html(response);
                    $('#dynamic_modal').appendTo("body").modal('show');

                    $('.i-checks').iCheck({
                        checkboxClass: 'icheckbox_square-green',
                        radioClass: 'iradio_square-green',
                    });
                    $('.modal select').select2();
                } else {
                    toastr.error(response.res);
                }
            },
            error: function (e, f, g) {
                console.log(e)
                console.log(f)
                console.log(g)
                toastr.error('AJAX backend error', 'An error has occured.');
            }
        });
    }

    function saveItem() {
        var lookup = $("#lookup").val();
        var token = $('@Html.AntiForgeryToken()').val();
        var item = {};
        $("#lookupdata *").each(function () {
            if ($(this).attr('name') !== undefined && $(this).val() !== '' && $(this).val() !== null) {
                if ($(this).attr("type") == 'checkbox')
                    item[$(this).attr('name')] = $(this).is(':checked');
                else
                    item[$(this).attr('name')] = $(this).val();
            }
        });

        $.ajax({
            url: '@Url.Action("Save", "DynamicLookup")',
            data: {
                item: JSON.stringify(item),
                lookup,
                __RequestVerificationToken: token,
            },
            type: "POST",
            beforeSend: function () {
                ShowLoadingScreen();
            },
            complete: function () {
                RemoveLoadingScreen();
            },
            success: function (response) {
                if (response.msg) {
                    closeModal();
                    toastr.success(response.res);
                    get("LookupName=" + $("#hid_lookupname").val());
                } else {
                    toastr.error(response.res);
                }
            },
            error: function () {
                toastr.error('AJAX backend error', 'An error has occured.');
            }
        });
    }
</script>